version: "3"

services:
  db:
    image: mysql
    container_name: local-mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local